#!/usr/bin/env bash
# A disjoint part of the supervision-host behavior suite; fixtures and cases
# stay in fm-supervision-host-helpers.sh so splitting never copies assertions.
# shellcheck source=tests/fm-supervision-host-helpers.sh
. "$(dirname "$0")/fm-supervision-host-helpers.sh"

test_claude_stop_hook_restores_handoff_when_successor_closed_before_exit_to_main
test_claude_stop_hook_restores_handoff_when_successor_closed_mid_engine_turn
test_claude_stop_hook_notifies_when_closed_successor_downtime_restore_fails
test_claude_stop_hook_notifies_when_closed_announced_successor_downtime_restore_fails
test_park_exit_probe_uses_half_second_child_sleeps
test_report_surface_enforces_actor_turn_and_scope
test_report_after_the_return_is_queued_for_main
test_dispatch_entry_scopes_rows_and_renders_the_away_tail
test_branch_outcomes_only_on_a_host_home_off_pi
test_branch_outcomes_put_captain_first_and_collapse_routine_overflow
test_branch_outcomes_collapse_repeated_captain_outcomes_per_task
test_branch_outcomes_present_a_long_away_window_once
test_branch_outcomes_budgets_count_bytes
test_branch_outcomes_stay_unread_when_a_projection_fails
test_branch_outcomes_stay_unread_without_jq
test_branch_outcomes_stay_unread_when_the_drain_cannot_print
test_branch_outcomes_date_a_legacy_backlog_without_adopting_it
test_branch_ack_keeps_older_keyed_decision_open
test_branch_outcomes_date_an_outcome_carried_across_a_switch_off_pi
test_branch_outcomes_keep_an_unshown_outcome_until_acknowledged
test_branch_outcomes_keep_a_drain_presented_outcome_across_a_switch_to_pi
test_branch_outcomes_keep_a_drain_presented_outcome_across_an_index_repair
test_attended_routine_wake_is_handled_on_the_engine_and_stays_off_main
test_attended_captain_outcome_reaches_main_through_branch_outcomes
test_captain_leaving_mid_turn_keeps_its_captain_outcome_for_the_return
test_quiet_record_without_its_daemon_is_a_present_captain
test_attended_main_only_close_passes_straight_to_main
test_off_written_while_parked_passes_the_next_attended_close_to_main
test_main_only_pass_through_leaves_the_successor_watcher_running
test_attended_close_with_unidentified_main_session_passes_to_main
test_close_accepted_away_that_turns_attended_passes_to_main
test_attended_close_that_turns_main_only_before_its_turn_passes_to_main
test_claude_stop_hook_delivers_a_main_only_pass_through
test_claude_stop_hook_rewakes_a_present_captain_beside_a_quiet_record
test_claude_stop_hook_runs_the_host_without_the_file_and_off_opts_out
test_claude_stop_hook_delivers_a_close_that_turns_main_only_at_its_turn
test_successor_left_at_the_turn_survives_the_hook_process_group_teardown
test_claude_stop_hook_notifies_when_at_turn_downtime_write_fails
test_successor_close_during_main_turn_is_delivered_at_the_next_turn_end
test_pass_through_successor_survives_the_hook_process_group_teardown
test_next_park_takes_over_the_cycle_a_pass_through_left_for_main
test_a_park_stopped_mid_take_over_leaves_the_take_over_to_the_next_park
test_unrecorded_successor_is_stopped_rather_than_left_for_main
test_primary_without_a_verified_mirror_runs_away_only
test_attended_wake_carries_the_dialog_mirror
test_dialog_bearing_files_are_owner_only
test_undelivered_dialog_is_fed_again_on_the_next_turn
test_attended_wake_with_an_unreadable_mirror_reaches_main
